version: '3'

services:

  php:
    container_name: picom_test_php
    image: yiisoftware/yii2-php:5.6-apache
    restart: 'always'
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
    links:
      - mysql

  mysql:
    container_name: picom_test_mysql
    image: mysql:5.7.24
    restart: 'always'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --innodb-use-native-aio=0

  phpmyadmin:
    container_name: picom_test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions